# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - echo "Your build and test goes here..."
      - step:
          name: 'Lint'
          script:
            - echo "Your linting goes here..."
      - step:
          name: 'Security scan'
          script:
            - echo "Your security scan goes here..."

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        script:
          - echo "Your deployment to staging script goes here..."
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "Your deployment to production script goes here..."
          - echo $NODE_ENV
          - echo $CLIENT_URL
          - echo $JWT_SECRET
          - echo $STRIPE_API
          - echo $TWITTER_API
          - echo $TWITTER_SECRET
          - echo $GOOGLE_CLIENT
          - echo $GOOGLE_SECRET
          - echo $GOOGLE_API
          - echo $FFMPEG_PATH
          - echo $FFPROBE_PATH
          - echo $AWS_KEY
          - echo $AWS_SECRET_KEY
          - echo $AWS_BUCKET
          - echo $YOUTUBE_CLIENT_ID
          - echo $YOUTUBE_SECRET
          - echo $REDIRECT_URL
          - echo $CLIENT_ID
          - echo $PROJECT_ID
          - echo $AUTH_URI
          - echo $TOKEN_URI
          - echo $AUTH_PROVIDER_X509_CERT_URL
          - echo $CLIENT_SECRET
          - echo $REDIRECT_URI
          - echo $JAVASCRIPT_ORIGIN
          - echo $REACT_APP_STRIPE_API
          - echo $REACT_APP_PAYPAL_API
          - echo $REACT_APP_API_URL
          - echo $REACT_APP_GOOGLE_API
          - echo $REACT_APP_FACEBOOK_API
          - echo $REACT_APP_INSTAGRAM_API
          - echo $REACT_APP_INSTAGRAM_SECRET
          - echo $REACT_APP_AWS_KEY
          - echo $REACT_APP_AWS_SECRET_KEY
          - echo $REACT_APP_BUCKET
          - echo $REACT_APP_MONDAY_BOARD_ID
          - echo $REACT_APP_MONDAY_API_KEY