# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

clone:
   depth: full

pipelines:
   branches:

     staging:
       - step:
           caches:
             - node
           script:
             - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/provids-staging.git integration:master
     

     production:
       - step:
           caches:
             - node
           script:
             - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/provids.git master:master
             
             
            
