# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2


pipelines:
  branches:
    staging:
      - step:
          name: 'Deploy to staging'
          script:
            - git fetch --all --unshallow
            - git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/provids-staging.git HEAD


    production:
      - step:
          name: 'Deploy to production'
          script:
            - git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/provids.git HEAD


    default:
      - step:
          name: 'Build and Test'
          script:
            - npm install
            - npm run test
