let {
  REACT_APP_STRIPE_API,
  REACT_APP_PAYPAL_API,
  REACT_APP_GOOGLE_API,
  REACT_APP_FACEBOOK_API,
  REACT_APP_INSTAGRAM_API,
  REACT_APP_INSTAGRAM_SECRET,
  REACT_APP_AWS_KEY,
  REACT_APP_AWS_SECRET_KEY,
  REACT_APP_BUCKET,
  REACT_APP_MONDAY_BOARD_ID,
  REACT_APP_MONDAY_API_KEY,
  REACT_APP_API_URL,
} = process.env;

REACT_APP_MONDAY_BOARD_ID = parseInt(REACT_APP_MONDAY_BOARD_ID);

export {
  REACT_APP_STRIPE_API,
  REACT_APP_PAYPAL_API,
  REACT_APP_GOOGLE_API,
  REACT_APP_FACEBOOK_API,
  REACT_APP_INSTAGRAM_API,
  REACT_APP_INSTAGRAM_SECRET,
  REACT_APP_AWS_KEY,
  REACT_APP_AWS_SECRET_KEY,
  REACT_APP_BUCKET,
  REACT_APP_MONDAY_BOARD_ID,
  REACT_APP_MONDAY_API_KEY,
  REACT_APP_API_URL,
};
